/**
 * 冻结的测试夹具（RFC-LOC-1 PR5b §4.1）。不是测试文件，App 代码从不 import 它。
 *
 * `./fixtures/` 下的 JSON 是 PR5b 删除 Legacy Adapter 与迁移规划之前，用当时的代码现场生成、再原样存下的中性测试数据
 * （生成函数与等价证明只在 PR5b 的第一个提交「Freeze test fixtures generated by the legacy code」里）。它们今后是静态数据：改代码不会让它们跟着变，
 * 派生结果由 ./derive.test.ts 的基线锁定钉住。每个函数每次都重新解析文件，返回新的对象（深拷贝），可以随意改。
 *
 * - `legacyIdCanonical(name)`：旧 id 空间的 Canonical（地点 id 是旧键，如 `iceland`、`iceland__reykjavik`、`wtg:<条目 id>`），
 *   原来由 `legacyAdapter(原始数据)` 得到。`deriveAppDataFromCanonical` 不看 id 的写法，照常派生。
 * - `v2SpaceCanonical(name)`：同一批数据直接搬进 V2 的 id 空间（UUIDv7、`legacyKeys` 带命名空间前缀），不合并地点；
 *   原来由 `toV2Space(legacyAdapter(原始数据)).data` 得到。`countryOfCityUuidOf()` 是其中 `countryOfCity` 的「旧 id → UUID」。
 * - `migratedCanonical(name)`：迁移规划合并之后的 Canonical（M）与写文件用的文件级元数据。
 * - `canonicalForInputsFixture()`：一份迁移后的五个 V2 文件与它的 M。
 *
 * 约束：Node 24 能直接加载——erasable-only TypeScript，相对 import 带 `.ts`，类型用 `import type`。
 */

/// <reference types="node" />

import { readFileSync } from 'node:fs'

import type { CanonicalData } from './types.ts'
import type { V2Files } from './v2Schema.ts'
import type { V2FileMeta } from './v2Serializer.ts'

const readFixture = <T,>(name: string): T => JSON.parse(readFileSync(new URL(`./fixtures/${name}`, import.meta.url), 'utf8')) as T

const entryOf = <T,>(file: string, name: string): T => {
  const all = readFixture<Record<string, T>>(file)
  if (!Object.hasOwn(all, name)) throw new Error(`fixture：${file} 里没有 ${name}`)
  return all[name]
}

/** 旧 id 空间的 Canonical 的名字（冻结文件里的键）。 */
export type LegacyIdCanonicalName =
  | 'sample' | 'personal' | 'personalDanglingMedia' | 'nameInconsistency' | 'countryOfCity' | 'alias'
  | 'classification1' | 'classification2' | 'classification3' | 'classification4' | 'classificationConsistent'
  | 'journeyRules1' | 'journeyRules2' | 'journeyRules3' | 'editorHidden'
  | 'addedCountriesConsistent' | 'addedCountriesShown' | 'addedCountriesHomeHidden'
  | 'planned' | 'media' | 'combined' | 'duplicate' | 'caseAndDiacritic'

export const LEGACY_ID_CANONICAL_NAMES: readonly LegacyIdCanonicalName[] = Object.freeze([
  'sample', 'personal', 'personalDanglingMedia', 'nameInconsistency', 'countryOfCity', 'alias',
  'classification1', 'classification2', 'classification3', 'classification4', 'classificationConsistent',
  'journeyRules1', 'journeyRules2', 'journeyRules3', 'editorHidden',
  'addedCountriesConsistent', 'addedCountriesShown', 'addedCountriesHomeHidden',
  'planned', 'media', 'combined', 'duplicate', 'caseAndDiacritic',
])

export const legacyIdCanonical = (name: LegacyIdCanonicalName): CanonicalData =>
  entryOf<CanonicalData>('legacy-id-canonical.json', name)

export type V2SpaceCanonicalName = 'sample' | 'personal' | 'nameInconsistency' | 'recordCoordinates' | 'countryOfCity'

export const V2_SPACE_CANONICAL_NAMES: readonly V2SpaceCanonicalName[] = Object.freeze([
  'sample', 'personal', 'nameInconsistency', 'recordCoordinates', 'countryOfCity',
])

export const v2SpaceCanonical = (name: V2SpaceCanonicalName): CanonicalData =>
  entryOf<CanonicalData>('v2-space-canonical.json', name)

/** `v2SpaceCanonical('countryOfCity')` 的「旧 id → UUID」。 */
export const countryOfCityUuidOf = (): Map<string, string> =>
  new Map(entryOf<[string, string][]>('v2-space-canonical.json', 'countryOfCityUuidOf'))

export type MigratedCanonicalName = 'sample' | 'personal' | 'nameInconsistency'

export const MIGRATED_CANONICAL_NAMES: readonly MigratedCanonicalName[] = Object.freeze(['sample', 'personal', 'nameInconsistency'])

export const migratedCanonical = (name: MigratedCanonicalName): { canonical: CanonicalData; fileMeta: Omit<V2FileMeta, 'placesGeneratedAt'> } =>
  entryOf('migrated-canonical.json', name)

export const canonicalForInputsFixture = (): { files: V2Files; migrated: CanonicalData } =>
  readFixture('canonical-for-inputs.json')
